"""Initial migrationclear

Revision ID: ffb67b7f03b3
Revises: 1f8c643f2b52
Create Date: 2024-07-09 10:08:58.030044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb67b7f03b3'
down_revision: Union[str, None] = '1f8c643f2b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amendments_actions',
    sa.Column('amendemnt_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('how', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('where', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('committees', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('links', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_summary',
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('as', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('congress_party_history',
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('partyAbbreviation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('partyName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startYear', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('endYear', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_amendments',
    sa.Column('amendment_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amendment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_bill:bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_bill:bill_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_bill:congress', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amends_bill:number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amends_treaty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chamber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('introduced_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('proposed_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:amendment_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:amendment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amends_amendment:purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('congress_leadership',
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('current', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_cosponsors',
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('district', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sponsored_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thomas_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('withdrawn_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('joined_at', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('amendment_actions',
    sa.Column('amendemnt_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('how', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('where', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('committees', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_actions',
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acted_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('committee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('in_committee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subcommittee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('how', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suspension', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('where', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calendar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('under', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('law', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('roll', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('in_subcommittee', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pocket', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_subjects',
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subjects', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('amendment_references',
    sa.Column('amendemnt_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('amendemnt_actions_links',
    sa.Column('amendemnt_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_info',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('latestAction_actionDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latestAction_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('originChamber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('originChamberCode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updateDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updateDateIncludingText', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latestAction_actionTime', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('congress_terms',
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chamber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('district', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('endYear', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memberType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startYear', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('stateCode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stateName', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_sponsors',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('district', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thomas_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bioguide_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('congress_members',
    sa.Column('bioguideId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthYear', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cosponsoredLegislation_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cosponsoredLegislation_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currentMember', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deathYear', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('depiction_attribution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('depiction_imageUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('directOrderName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invertedOrderName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sponsoredLegislation_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sponsoredLegislation_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updateDate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('district', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('middleName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('honorificName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addressInformation_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addressInformation_district', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addressInformation_officeAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addressInformation_phoneNumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('addressInformation_zipCode', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('officialWebsiteUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nickName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suffixName', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('bill_related_bills',
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('voting_records',
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('party', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    op.create_table('voting_info',
    sa.Column('amendment_author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amendment_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amendment_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chamber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('congress', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requires', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vote_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amendment_purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nomination_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nomination_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treaty_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_modified', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treaty_congress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treaty_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.TEXT(), autoincrement=False, nullable=True),
    schema='raw'
    )
    # ### end Alembic commands ###
